spring:
  application:
    name: REDDIS-SERVER
  config:    name: REDDIS-SERVER
  profiles:    active:    - default 
server:
  port: 8000
eureka:
  client:
    service-url:
      deafultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true